# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('isSelected', models.BooleanField(default=False)),
                ('votes', models.IntegerField(default=0)),
                ('uniqueId', models.CharField(default=None, max_length=24, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('isMultiSelect', models.BooleanField(default=False)),
                ('uniqueId', models.CharField(max_length=24, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='PollApp.Poll'),
        ),
    ]
